export * from './home/MainTitle/MainTitle'
export * from './home/WhyDoU/WhyDoU'
export * from './home/AboutUs/AboutUs'
export * from './home/OurServices/OurServices'
export * from './home/Portfolio/Portfolio'
export * from './home/TechStack/TechStack'
export * from './home/Contacts/Contact'
