import "../../assets/style/style.scss";
import type { Metadata } from "next";
import ProgressBar from "@/components/layout/ProgressBar/ProgressBar";
import ContactButton from "@/components/layout/ContactButton/ContactButton";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export const metadata: Metadata = {
  title: "Создание сайта под ключ",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0, user-scalable=no",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <script
          dangerouslySetInnerHTML={{
            __html: `
                (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
                m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
                (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
      
                ym(95231553, "init", {
                      clickmap:true,
                      trackLinks:true,
                      accurateTrackBounce:true
                });
              `,
          }}
        />
        <noscript>
          <div>
            <img
              src='https://mc.yandex.ru/watch/95231553'
              style={{ position: "absolute", left: "-9999px" }}
              alt=''
            />
          </div>
        </noscript>
        <ToastContainer
          position='top-right'
          autoClose={4000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover={false}
          theme='dark'
        />
        <ProgressBar />
        <ContactButton />
        {children}
      </body>
    </html>
  );
}
